#!/bin/bash
set -e
cp -f external/npm/node_modules/mathjax/es5/a11y/assistive-mml.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/a11y/assistive-mml.js
cp -f external/npm/node_modules/mathjax/es5/a11y/complexity.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/a11y/complexity.js
cp -f external/npm/node_modules/mathjax/es5/a11y/explorer.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/a11y/explorer.js
cp -f external/npm/node_modules/mathjax/es5/a11y/semantic-enrich.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/a11y/semantic-enrich.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/action.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/action.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/all-packages.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/all-packages.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/ams.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/ams.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/amscd.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/amscd.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/autoload.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/autoload.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/bbox.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/bbox.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/boldsymbol.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/boldsymbol.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/braket.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/braket.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/bussproofs.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/bussproofs.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/cancel.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/cancel.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/centernot.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/centernot.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/color.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/color.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/colortbl.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/colortbl.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/colorv2.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/colorv2.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/configmacros.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/configmacros.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/enclose.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/enclose.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/extpfeil.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/extpfeil.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/gensymb.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/gensymb.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/html.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/html.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/mathtools.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/mathtools.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/mhchem.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/mhchem.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/newcommand.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/newcommand.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/noerrors.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/noerrors.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/noundefined.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/noundefined.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/physics.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/physics.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/require.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/require.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/setoptions.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/setoptions.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/tagformat.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/tagformat.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/textcomp.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/textcomp.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/textmacros.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/textmacros.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/unicode.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/unicode.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/upgreek.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/upgreek.js
cp -f external/npm/node_modules/mathjax/es5/input/tex/extensions/verb.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/input/tex/extensions/verb.js
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff
cp -f external/npm/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Zero.woff
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/de.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/de.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/en.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/en.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/es.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/es.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/fr.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/fr.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/hi.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/hi.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/it.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/it.js
cp -f external/npm/node_modules/mathjax/es5/sre/mathmaps/nemeth.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/mathmaps/nemeth.js
cp -f external/npm/node_modules/mathjax/es5/sre/sre-node.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/sre-node.js
cp -f external/npm/node_modules/mathjax/es5/sre/sre_browser.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/sre/sre_browser.js
cp -f external/npm/node_modules/mathjax/es5/tex-chtml.js bazel-out/k8-fastbuild/bin/qt/aqt/data/web/js/vendor/mathjax/tex-chtml.js