chmod -x AnkiDroid/src/main/assets/mathjax/a11y/assistive-mml.js
chmod -x AnkiDroid/src/main/assets/mathjax/a11y/complexity.js
chmod -x AnkiDroid/src/main/assets/mathjax/a11y/explorer.js
chmod -x AnkiDroid/src/main/assets/mathjax/a11y/semantic-enrich.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/action.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/all-packages.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/ams.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/amscd.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/autoload.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/bbox.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/boldsymbol.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/braket.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/bussproofs.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/cancel.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/centernot.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/color.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/colortbl.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/colorv2.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/configmacros.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/enclose.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/extpfeil.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/gensymb.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/html.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/mathtools.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/mhchem.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/newcommand.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/noerrors.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/noundefined.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/physics.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/require.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/setoptions.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/tagformat.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/textcomp.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/textmacros.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/unicode.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/upgreek.js
chmod -x AnkiDroid/src/main/assets/mathjax/input/tex/extensions/verb.js
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff
chmod -x AnkiDroid/src/main/assets/mathjax/output/chtml/fonts/woff-v2/MathJax_Zero.woff
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/de.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/en.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/es.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/fr.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/hi.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/it.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/mathmaps/nemeth.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/sre-node.js
chmod -x AnkiDroid/src/main/assets/mathjax/sre/sre_browser.js
chmod -x AnkiDroid/src/main/assets/mathjax/tex-chtml.js