name: Sync Translations

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync_translations:
    permissions:
      contents: write  # for Git to git push
    name: 'Sync Translations with Crowdin'
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Credential Prep
        run: |
          echo "CROWDIN_API_KEY=${{ secrets.CROWDIN_API_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: GIT Setup
        run: |
          git config --global user.name 'AnkiDroid Translations'
          git config --global user.email 'ankidroid@ankidroid.org'
          git checkout -b i18n_sync
          git reset --hard origin/main
        shell: bash

      - name: Credential Prep
        run: |
          echo "${{ secrets.CROWDIN_API_KEY }}" > ./tools/localization/.env
        shell: bash

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies and build
        run: |
          cd ./tools/localization
          yarn install
          yarn build

      - name: Push translation sources to crowdin
        run: |
          cd ./tools/localization
          yarn start upload

      - name: Pull translation updates from crowdin
        run: |
          cd ./tools/localization
          yarn start download
      
      - name: Extract downloaded ankidroid.zip file
        run: |
          cd ./tools/localization
          yarn start extract
      
      - name: Update translation to AnkiDroid res
        run: |
          cd ./tools/localization
          yarn start update
        
      - name: Find broken strings
        run: |
          echo "Checking translations for known classes of error."
          echo "(Note that if errors are found and you correct on crowdin, they make you wait 30 minutes for a new zip build)"
          chmod +x ./tools/find-broken-strings-variables.sh
          ./tools/find-broken-strings-variables.sh
  
      - name: Commit changes
        run: |
          git add docs/marketing/localized_description AnkiDroid/src/main/res/values*
          git commit -am 'Updated strings from Crowdin'
          git push --set-upstream origin +i18n_sync
          echo "The results of the sync are on the i18n_sync branch, PR them from there for merge."
          echo "https://github.com/ankidroid/Anki-Android/compare/i18n_sync?expand=1"
