name: Sync Translations

on:
  workflow_dispatch:

jobs:
  sync_translations:
    name: 'Sync Translations with Crowdin'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Credential Prep
        run: |
          echo "CROWDIN_API_KEY=${{ secrets.CROWDIN_API_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: GIT Setup
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout -b i18n_sync
          git reset --hard origin/main
        shell: bash

      - name: Credential Prep
        run: |
          echo "${{ secrets.CROWDIN_API_KEY }}" > ./tools/localization/.env
        shell: bash

      - name: Setup nodejs and yarn
        run: |
          sudo apt install npm -y
          sudo npm install yarn -g
      
      - name: Install dependencies and build
        run: |
          cd ./tools/localization
          yarn install
          yarn build

      - name: Push translation sources to crowdin
        run: |
          cd ./tools/localization
          yarn start upload

      - name: Pull translation updates from crowdin
        run: |
          cd ./tools/localization
          yarn start download
      
      - name: Extract downloaded ankidroid.zip file
        run: |
          cd ./tools/localization
          yarn start extract
      
      - name: Update translation to AnkiDroid res
        run: |
          cd ./tools/localization
          yarn start update
        
      - name: Commit changes
        run: |
          git add docs/marketing/localized_description AnkiDroid/src/main/res/values*
          git commit -am 'Updated strings from Crowdin'
          git push --set-upstream origin +i18n_sync
          echo "The results of the sync are on the i18n_sync branch, PR them from there for merge."
          echo "https://github.com/ankidroid/Anki-Android/compare/i18n_sync?expand=1"
